image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew


stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

unitTests:
  stage: test
  script:
    - ./gradlew test

#functionalTests:
#  stage: test
#  script:
#    - ./gradlew cAT
